"""Initial schema: entity, source, deal, evidence_span.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-09

Hand-written rather than autogenerated — this is the bootstrap migration
and there's no live database to diff against yet. Mirrors the SQLModel
table definitions in ``src/midas/models/``.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# JSONB on Postgres, JSON elsewhere — matches midas.models._columns.JSON_VARIANT.
JSON_VARIANT = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def upgrade() -> None:
    """Create all four tables and their indexes."""
    op.create_table(
        "entity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("aliases", JSON_VARIANT, nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=True),
        sa.Column("cik", sa.String(length=16), nullable=True),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("sector_tags", JSON_VARIANT, nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_entity_canonical_name",
        "entity",
        ["canonical_name"],
        unique=True,
    )
    op.create_index(
        "ix_entity_ticker_unique",
        "entity",
        ["ticker"],
        unique=True,
        postgresql_where=sa.text("ticker IS NOT NULL"),
    )
    op.create_index(
        "ix_entity_cik_unique",
        "entity",
        ["cik"],
        unique=True,
        postgresql_where=sa.text("cik IS NOT NULL"),
    )

    op.create_table(
        "source",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("publisher", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_source_url", "source", ["url"], unique=False)
    op.create_index("ix_source_source_type", "source", ["source_type"], unique=False)
    op.create_index(
        "ix_source_content_sha256",
        "source",
        ["content_sha256"],
        unique=True,
    )
    op.create_index(
        "ix_source_type_published_at",
        "source",
        ["source_type", "published_at"],
        unique=False,
    )

    op.create_table(
        "deal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("from_entity_id", sa.Uuid(), nullable=False),
        sa.Column("to_entity_id", sa.Uuid(), nullable=False),
        sa.Column("deal_type", sa.String(length=32), nullable=False),
        sa.Column("amount_usd", sa.Numeric(20, 2), nullable=True),
        sa.Column("amount_native", sa.Numeric(20, 2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("announced_at", sa.Date(), nullable=True),
        sa.Column("closes_at", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["from_entity_id"], ["entity.id"]),
        sa.ForeignKeyConstraint(["to_entity_id"], ["entity.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_deal_from_entity_id", "deal", ["from_entity_id"], unique=False)
    op.create_index("ix_deal_to_entity_id", "deal", ["to_entity_id"], unique=False)
    op.create_index("ix_deal_deal_type", "deal", ["deal_type"], unique=False)
    op.create_index("ix_deal_announced_at", "deal", ["announced_at"], unique=False)
    op.create_index(
        "ix_deal_from_announced",
        "deal",
        ["from_entity_id", "announced_at"],
        unique=False,
    )
    op.create_index(
        "ix_deal_to_announced",
        "deal",
        ["to_entity_id", "announced_at"],
        unique=False,
    )

    op.create_table(
        "evidence_span",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("text_snippet", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("extractor", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["deal_id"], ["deal.id"]),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_evidence_span_deal_id", "evidence_span", ["deal_id"], unique=False)
    op.create_index("ix_evidence_span_source_id", "evidence_span", ["source_id"], unique=False)
    op.create_index(
        "ix_evidence_deal_source",
        "evidence_span",
        ["deal_id", "source_id"],
        unique=False,
    )


def downgrade() -> None:
    """Drop every object created by :func:`upgrade`, in reverse FK order."""
    op.drop_index("ix_evidence_deal_source", table_name="evidence_span")
    op.drop_index("ix_evidence_span_source_id", table_name="evidence_span")
    op.drop_index("ix_evidence_span_deal_id", table_name="evidence_span")
    op.drop_table("evidence_span")

    op.drop_index("ix_deal_to_announced", table_name="deal")
    op.drop_index("ix_deal_from_announced", table_name="deal")
    op.drop_index("ix_deal_announced_at", table_name="deal")
    op.drop_index("ix_deal_deal_type", table_name="deal")
    op.drop_index("ix_deal_to_entity_id", table_name="deal")
    op.drop_index("ix_deal_from_entity_id", table_name="deal")
    op.drop_table("deal")

    op.drop_index("ix_source_type_published_at", table_name="source")
    op.drop_index("ix_source_content_sha256", table_name="source")
    op.drop_index("ix_source_source_type", table_name="source")
    op.drop_index("ix_source_url", table_name="source")
    op.drop_table("source")

    op.drop_index("ix_entity_cik_unique", table_name="entity")
    op.drop_index("ix_entity_ticker_unique", table_name="entity")
    op.drop_index("ix_entity_canonical_name", table_name="entity")
    op.drop_table("entity")
